name: wevote

services:
  db:
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-wevoteserverdb}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16-alpine
    networks:
      - back_end
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  aws:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    image: localstack/localstack
    networks:
      - back_end
    profiles:
      - optional
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  api:
    build:
      dockerfile: docker/Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - DATABASE_NAME=${DATABASE_NAME:-wevoteserverdb}
      - DATABASE_NAME_READONLY=${DATABASE_NAME:-wevoteserverdb}
      - DATABASE_HOST=db
      - DATABASE_HOST_READONLY=db
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_USER_READONLY=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-admin}
      - DATABASE_PASSWORD_READONLY=${DATABASE_PASSWORD:-admin}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_PORT_READONLY=${DATABASE_PORT:-5432}
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
    volumes:
      - .:/wevote/code
    networks:
      - back_end
    ports:
      - "127.0.0.1:8000:8000"

networks:
  back_end:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"


volumes:
  localstack:
  postgres_data:
